In [4]:
import numpy as np
from sklearn.preprocessing import OneHotEncoder


In [3]:
X = np.array([['A'],['A'], ['B'], ['C']])
X

array([['A'],
       ['A'],
       ['B'],
       ['C']], dtype='<U1')

In [5]:
enc = OneHotEncoder()

In [7]:
enc.fit_transform(X).todense() # Mudança de dimensão

matrix([[1., 0., 0.],
        [1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

Output with dense matrix

In [9]:
enc = OneHotEncoder(sparse_output=False)
enc.fit_transform(X)

array([[1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Removing one dummy variable

In [10]:
enc = OneHotEncoder(sparse_output=False, drop='first')
enc.fit_transform(X)

array([[0., 0.],
       [0., 0.],
       [1., 0.],
       [0., 1.]])

Removing one dummy variable from binary features

In [11]:
X = np.array([['A'],['A'], ['A'], ['C']])
X

array([['A'],
       ['A'],
       ['A'],
       ['C']], dtype='<U1')

In [16]:
enc = OneHotEncoder(sparse_output=False, drop='if_binary')
enc.fit_transform(X)

array([[0.],
       [0.],
       [0.],
       [1.]])

Error handling