In [44]:
import numpy as np
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder
from sklearn.compose import ColumnTransformer


In [23]:
X = np.array([['X', 'High'], ['Y', 'Low'], ['Z', 'Medium'], ['X', 'Low']])

Ordenando com One Hot

In [4]:
enc = OneHotEncoder(sparse_output=False, categories = [['X', 'Y', 'Z'], ['Low','Medium','High']])
enc.fit_transform(X)

array([[1., 0., 0., 0., 0., 1.],
       [0., 1., 0., 1., 0., 0.],
       [0., 0., 1., 0., 1., 0.],
       [1., 0., 0., 1., 0., 0.]])

Ordenando com One Hot e Ordinal

In [5]:
enc = OneHotEncoder(sparse_output=False, categories = [['X','Y','Z']])
enc2 = OrdinalEncoder(categories=[['Low','Medium','High']])

In [54]:
X1 = enc.fit_transform(X[:,:1])


In [26]:
X2 = enc2.fit_transform(X[:,1:])

In [56]:
X3 =[np.append(X1[x], X2[x]) for x in range(0, len(X1))]
X3


[array([1., 0., 0., 2.]),
 array([0., 1., 0., 0.]),
 array([0., 0., 1., 1.]),
 array([1., 0., 0., 0.])]

Usando Column Transformer


In [47]:
encoder = ColumnTransformer([
    ('first_column', OneHotEncoder(),[0]),
    ('second_column', OrdinalEncoder(categories=[['Low', 'Medium', 'High']]), [1])
])

In [48]:
encoder.fit_transform(X)

array([[1., 0., 0., 2.],
       [0., 1., 0., 0.],
       [0., 0., 1., 1.],
       [1., 0., 0., 0.]])

Exercise 2


In [57]:
encoder = ColumnTransformer([
    ('fist_column', OneHotEncoder(categories=[['X', 'Y', 'Z', 'W']]),[0]),
    ('second_column', OrdinalEncoder(categories=[['Low', 'Medium', 'High', 'Very high']]), [1])
])

In [58]:
encoder.fit_transform(X)


array([[1., 0., 0., 0., 2.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 1.],
       [1., 0., 0., 0., 0.]])

In [59]:
Y = [['W', 'Very high']]
encoder.transform(Y)

array([[0., 0., 0., 1., 3.]])