In [9]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("C:\\Users\\Nitro\\Desktop\\Inteligencia_Artificial\\PreProcessamento_Udemy\\sample_dataset.csv")

In [5]:
X = df.iloc[:,0:3].dropna()
X

mean radius  mean texture  mean perimeter
1          20.57         17.77          132.90
2          19.69         21.25          130.00
3          11.42         20.38           77.58
5          12.45         15.70           82.57
7          13.71         20.83           90.20
..           ...           ...             ...
562        15.22         30.62          103.40
563        20.92         25.09          143.00
564        21.56         22.39          142.00
566        16.60         28.08          108.30
567        20.60         29.33          140.10

[385 rows x 3 columns]

Normalization 0-1 Scaling

In [6]:
from sklearn.preprocessing import MinMaxScaler

In [7]:
scaler = MinMaxScaler()

In [8]:
X_scaled = scaler.fit_transform(X)
X_scaled

array([[0.63004759, 0.27257355, 0.60432679],
       [0.58687012, 0.3902604 , 0.58368915],
       [0.18110004, 0.36083869, 0.21064617],
       ...,
       [0.67862225, 0.42881299, 0.66908625],
       [0.43525833, 0.62123774, 0.42926274],
       [0.63151955, 0.66351031, 0.65556504]], shape=(385, 3))

In [10]:
np.apply_over_axes(np.max, X_scaled, 0)

array([[1., 1., 1.]])

In [11]:
np.apply_over_axes(np.min, X_scaled, 0)

array([[0., 0., 0.]])

Standarlization

In [12]:
from sklearn.preprocessing import StandardScaler

In [14]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled

array([[ 1.87149535, -0.35527432,  1.7252216 ],
       [ 1.61663638,  0.44774298,  1.6034021 ],
       [-0.77845877,  0.24698866, -0.59859036],
       ...,
       [ 2.1582117 ,  0.71080038,  2.10748279],
       [ 0.72173384,  2.02377982,  0.6918562 ],
       [ 1.88018373,  2.31221994,  2.02767001]], shape=(385, 3))

In [15]:
np.apply_over_axes(np.mean, X_scaled, 0)

array([[-7.38226219e-17, -2.86062660e-16, -1.84556555e-17]])

In [16]:
np.apply_over_axes(np.var, X_scaled, 0)

array([[1., 1., 1.]])

Robust scaling

In [17]:
from sklearn.preprocessing import RobustScaler

In [18]:
scaler = RobustScaler()
X_scaled = scaler.fit_transform(X)
X_scaled

array([[ 1.78484108, -0.18650089,  1.64689365],
       [ 1.56968215,  0.43161634,  1.54510355],
       [-0.45232274,  0.27708703, -0.29484029],
       ...,
       [ 2.02689487,  0.63410302,  1.96630397],
       [ 0.81418093,  1.64476021,  0.78343278],
       [ 1.79217604,  1.86678508,  1.8996139 ]], shape=(385, 3))

In [19]:
np.apply_over_axes(np.median, X_scaled, 0)

array([[0., 0., 0.]])

In [20]:
scaler.inverse_transform(X_scaled)

array([[ 20.57,  17.77, 132.9 ],
       [ 19.69,  21.25, 130.  ],
       [ 11.42,  20.38,  77.58],
       ...,
       [ 21.56,  22.39, 142.  ],
       [ 16.6 ,  28.08, 108.3 ],
       [ 20.6 ,  29.33, 140.1 ]], shape=(385, 3))