In [14]:
import numpy as np
from sklearn.preprocessing import KBinsDiscretizer
import pandas as pd

In [5]:
df = pd.read_csv("C:\\Users\\Nitro\\Desktop\\Inteligencia_Artificial\\PreProcessamento_Udemy\\sample_dataset.csv").iloc[:, 0:5].dropna()
df

mean radius  mean texture  mean perimeter  mean area  mean smoothness
2          19.69         21.25          130.00     1203.0          0.10960
3          11.42         20.38           77.58      386.1          0.14250
8          13.00         21.82           87.50      519.8          0.12730
13         15.85         23.95          103.70      782.7          0.08401
14         13.73         22.61           93.60      578.3          0.11310
..           ...           ...             ...        ...              ...
549        10.82         24.21           68.89      361.6          0.08192
550        10.86         21.48           68.51      360.5          0.07431
560        14.05         27.15           91.38      600.4          0.09929
564        21.56         22.39          142.00     1479.0          0.11100
567        20.60         29.33          140.10     1265.0          0.11780

[176 rows x 5 columns]

Bins with uniform width

In [3]:
binner = KBinsDiscretizer(strategy='uniform', n_bins=5)
binner.fit_transform(df)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 880 stored elements and shape (176, 25)>

In [4]:
binner = KBinsDiscretizer(strategy='uniform', n_bins=5, encode = 'onehot-dense')
binner.fit_transform(df)

array([[0., 0., 1., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 0., 1.],
       ...,
       [0., 1., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], shape=(176, 25))

In [6]:
binner = KBinsDiscretizer(strategy='uniform', n_bins=5, encode = 'ordinal')
binner.fit_transform(df)

array([[2., 1., 2., 2., 2.],
       [0., 1., 0., 0., 4.],
       [1., 2., 1., 0., 4.],
       [1., 2., 1., 1., 1.],
       [1., 2., 1., 0., 3.],
       [2., 2., 2., 2., 2.],
       [1., 1., 1., 0., 2.],
       [0., 0., 0., 0., 2.],
       [2., 1., 2., 1., 3.],
       [1., 1., 1., 0., 2.],
       [2., 2., 2., 1., 3.],
       [2., 2., 2., 2., 1.],
       [1., 1., 1., 0., 1.],
       [1., 1., 1., 0., 2.],
       [2., 2., 2., 1., 1.],
       [1., 1., 1., 0., 2.],
       [2., 1., 2., 1., 2.],
       [0., 1., 0., 0., 1.],
       [2., 1., 2., 1., 3.],
       [1., 1., 1., 0., 1.],
       [0., 0., 0., 0., 2.],
       [0., 0., 0., 0., 0.],
       [1., 2., 1., 0., 3.],
       [0., 1., 0., 0., 2.],
       [0., 0., 0., 0., 2.],
       [1., 1., 1., 0., 2.],
       [1., 0., 1., 0., 4.],
       [3., 2., 3., 2., 4.],
       [0., 1., 0., 0., 2.],
       [1., 0., 1., 0., 4.],
       [1., 1., 1., 0., 0.],
       [0., 1., 0., 0., 3.],
       [2., 1., 2., 1., 2.],
       [2., 1., 2., 2., 1.],
       [1., 1.

Binning using quantiles

In [11]:
binner = KBinsDiscretizer(strategy='quantile', n_bins=5, encode = 'ordinal')
binner.fit_transform(df)

C:\Users\Nitro\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\preprocessing\_discretization.py:296: FutureWarning: The current default behavior, quantile_method='linear', will be changed to quantile_method='averaged_inverted_cdf' in scikit-learn version 1.9 to naturally support sample weight equivalence properties by default. Pass quantile_method='averaged_inverted_cdf' explicitly to silence this warning.
  warnings.warn(


array([[4., 3., 4., 4., 4.],
       [0., 3., 1., 0., 4.],
       [2., 3., 2., 2., 4.],
       [3., 4., 3., 3., 0.],
       [2., 4., 3., 2., 4.],
       [4., 3., 4., 4., 2.],
       [2., 1., 2., 2., 3.],
       [0., 0., 0., 0., 3.],
       [3., 1., 3., 3., 4.],
       [3., 3., 3., 3., 3.],
       [3., 4., 3., 3., 4.],
       [4., 4., 4., 4., 2.],
       [2., 2., 2., 2., 1.],
       [2., 3., 2., 2., 3.],
       [4., 4., 4., 4., 1.],
       [2., 3., 2., 2., 3.],
       [4., 1., 4., 4., 4.],
       [1., 2., 1., 1., 0.],
       [4., 2., 4., 4., 4.],
       [2., 2., 2., 2., 0.],
       [0., 0., 0., 0., 2.],
       [0., 0., 0., 0., 0.],
       [1., 4., 2., 1., 4.],
       [0., 1., 0., 0., 3.],
       [0., 0., 0., 0., 2.],
       [2., 1., 2., 2., 3.],
       [2., 0., 2., 2., 4.],
       [4., 4., 4., 4., 4.],
       [0., 2., 0., 0., 2.],
       [2., 0., 2., 2., 4.],
       [3., 2., 3., 3., 0.],
       [0., 3., 0., 0., 4.],
       [4., 1., 4., 4., 3.],
       [4., 2., 4., 4., 0.],
       [3., 1.

In [16]:
np.unique(binner.fit_transform(df)[:,0], return_counts=True) # Retorna o número de cada elemento na lista

C:\Users\Nitro\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\preprocessing\_discretization.py:296: FutureWarning: The current default behavior, quantile_method='linear', will be changed to quantile_method='averaged_inverted_cdf' in scikit-learn version 1.9 to naturally support sample weight equivalence properties by default. Pass quantile_method='averaged_inverted_cdf' explicitly to silence this warning.
  warnings.warn(


(array([0., 1., 2., 3., 4.]), array([35, 35, 35, 35, 36]))

Binning using K-Means

In [17]:
binner = KBinsDiscretizer(strategy='kmeans', n_bins=3, encode = 'ordinal')
binner.fit_transform(df)

array([[1., 1., 2., 1., 1.],
       [0., 1., 0., 0., 2.],
       [0., 1., 0., 0., 2.],
       [1., 2., 1., 0., 0.],
       [0., 1., 1., 0., 2.],
       [1., 1., 2., 1., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [1., 0., 1., 1., 2.],
       [0., 1., 1., 0., 1.],
       [1., 2., 1., 1., 2.],
       [1., 2., 2., 1., 1.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 1.],
       [1., 2., 2., 1., 0.],
       [0., 1., 0., 0., 1.],
       [1., 0., 2., 1., 1.],
       [0., 1., 0., 0., 0.],
       [1., 1., 2., 1., 2.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 2., 0., 0., 2.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 1.],
       [0., 0., 0., 0., 2.],
       [1., 2., 2., 1., 2.],
       [0., 1., 0., 0., 1.],
       [0., 0., 0., 0., 2.],
       [0., 1., 1., 0., 0.],
       [0., 1., 0., 0., 2.],
       [1., 0., 2., 1., 1.],
       [1., 1., 2., 1., 0.],
       [0., 0.