In [1]:
from sklearn.datasets import load_wine

from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import SMOTE
import numpy as np

In [2]:
X, y = load_wine(return_X_y=True)

In [4]:
np.unique(y, return_counts=True)

(array([0, 1, 2]), array([59, 71, 48]))

In [5]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [6]:
res = SMOTE(random_state=0)

In [7]:
X_res, y_res = res.fit_resample(X_scaled, y)

In [8]:
X_res

array([[ 1.51861254, -0.5622498 ,  0.23205254, ...,  0.36217728,
         1.84791957,  1.01300893],
       [ 0.24628963, -0.49941338, -0.82799632, ...,  0.40605066,
         1.1134493 ,  0.96524152],
       [ 0.19687903,  0.02123125,  1.10933436, ...,  0.31830389,
         0.78858745,  1.39514818],
       ...,
       [ 0.06334972,  2.24313817,  0.39107263, ..., -1.73648411,
        -1.09841643, -0.30886394],
       [ 0.97276512,  0.54537381, -0.2036003 , ..., -1.20664012,
        -1.32359186, -0.47814445],
       [ 0.0508642 ,  1.83729472,  0.41481959, ..., -1.60395346,
        -1.19906182, -0.25914019]], shape=(213, 13))

In [9]:
y_res

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [10]:
np.unique(y_res, return_counts=True)

(array([0, 1, 2]), array([71, 71, 71]))

In [11]:
scaler.inverse_transform(X_res)

array([[1.42300000e+01, 1.71000000e+00, 2.43000000e+00, ...,
        1.04000000e+00, 3.92000000e+00, 1.06500000e+03],
       [1.32000000e+01, 1.78000000e+00, 2.14000000e+00, ...,
        1.05000000e+00, 3.40000000e+00, 1.05000000e+03],
       [1.31600000e+01, 2.36000000e+00, 2.67000000e+00, ...,
        1.03000000e+00, 3.17000000e+00, 1.18500000e+03],
       ...,
       [1.30519023e+01, 4.83521237e+00, 2.47350349e+00, ...,
        5.61655035e-01, 1.83401396e+00, 6.49903291e+02],
       [1.37881131e+01, 2.94389672e+00, 2.31081745e+00, ...,
        6.82421637e-01, 1.67459127e+00, 5.96745547e+02],
       [1.30417947e+01, 4.38310129e+00, 2.48000000e+00, ...,
        5.91862561e-01, 1.76275770e+00, 6.65517626e+02]], shape=(213, 13))